name: Build Panoramix

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar entorno de Visual Studio
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configurar proyecto
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Compilar
        run: cmake --build build --config Release

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: Panoramix-VST3-Windows
          path: build/Panoramix_artefacts/Release/VST3/
